### ISSUE TITLE
Missing text on Vector Tiles docs due to font-awesome bug

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#104]
Console on page https://mapzen.com/documentation/vector-tiles/use-service/:

```
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (documentation.css, line 3128)
[Warning] Unexpected CSS token: : (documentation.css, line 3136)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery-1.10.2.min.map, line 0)
```

In Safari 9.0.2, looks like:

<img width="710" alt="fonts" src="https://cloud.githubusercontent.com/assets/58730/12378982/3f2316f2-bd04-11e5-95bd-164dae5fb97c.png">

**Comment by migurski** [comment]
Hm, the font appeared correctly when I returned to the page later. Not liking the unpredictability of this.

**Comment by louh** [comment]
Not sure what would be causing this, though...

**Comment by migurski** [comment]
I’ll keep an eye out for it, but I will close this ticket for now.
