### ISSUE TITLE
Add minimum page skeleton template

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#106]
What’s the smallest-possible page template to make the styleguide work? CSS include, mobile-friendly meta tags, script tags, container div? 

Provide or link it at the top of the styleguide.

**Comment by louh** [comment]
Something like this. https://gist.github.com/louh/9b1113c88b4fe82fb61e

**Comment by migurski** [comment]
Yes, something like that.

**Comment by migurski** [comment]
(ideally a little slimmer, but yes)

**Comment by migurski** [comment]
Should it be visible from http://precog.mapzen.com/mapzen/styleguide/master/ ? I also think the boilerplate and the how-to are the same thing, not different.

**Comment by souperneon** [comment]
I really like rizzo has done this. Something we had talked about yesterday, the idea of layout boilerplates. http://rizzo.lonelyplanet.com/documentation/page-layout/core-layouts

It feels weird to embed it in a page, I think we should just link it from the how-to section and put the code in a <pre> tag maybe?

**Comment by migurski** [comment]
Embedding in a page will allow us to describe it, and will implicitly limit its complexity. Let’s definitely embed it as we talked about earlier this morning.
