### ISSUE TITLE
Messaging styleguide

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/styleguide#111]
- are we doing this? ex.https://style.codeforamerica.org/messaging/ @louh @rmglennon @burritojustice ?

**Comment by louh** [comment]
We'd talked about moving @rmglennon 's content guidelines from https://github.com/mapzen/ui/tree/master/guides to https://github.com/mapzen/wiki/wiki -- is that still a thing?

**Comment by hanbyul-here** [comment]
I can manually copy the contents from the repo, or we just can put links to the github wiki if it is happening

**Comment by migurski** [comment]
Let’s link for now; the guidelines should stay where Rhonda put them.

**Comment by souperneon** [comment]
Adding them as links in the resources section
