### ISSUE TITLE
add version number to styleguide header

### ISSUE THREAD

**Issue by souperneon** [mapzen/styleguide#118]

**Comment by souperneon** [comment]
@migurski any ideas on how to address this? 
We landing page being the most current version but the embed link having the version number so we don't break anything. 
We should also display version number in the header right under where it says 'mapzen web styleguide'. In the future this can be a dropdown to link to older versions.

**Comment by migurski** [comment]
I talked with @sleepylemur a little about this, I think that we want to keep version numbers out of the URLs for as long as possible. For now, let’s stick with `https://mapzen.com/common/styleguide` as the one true location, and keep an eye on any possible breaking changes which may require us to move or version the thing.

**Comment by souperneon** [comment]
future problem! thanks :)

**Comment by migurski** [comment]
Great, closing.
