### ISSUE TITLE
add grids to design-elements

### ISSUE THREAD

**Issue by souperneon** [mapzen/styleguide#119]
for v1, reference bootstrap grids 
for future, display and talk about responsiveness etc. Show different possibilities of layouts with the grid graphically and link to html boilerplates for each layout

**Comment by hanbyul-here** [comment]
Is this going to be part of design elements?

**Comment by souperneon** [comment]
not sure yet. Still figuring out how to represent this.

**Comment by souperneon** [comment]
http://styleguide.cfapps.io/react_utilities_grids.html
https://www.lightningdesignsystem.com/components/grid-system

**Comment by migurski** [comment]
I’m going to pull this ticket out of “ready”, since we talked about it as lower priority, and there’s a lot of stuff already in the read/in-progress groups.
