### ISSUE TITLE
add loading spinner to ui-components

### ISSUE THREAD

**Issue by souperneon** [mapzen/styleguide#120]
I think we only use it in the button on developer but it's a useful one to have in the list and we should use it more often especially in demos

**Comment by louh** [comment]
we have some variations on this
- the "Locate me" button on Map UI has a spinner
- the Leaflet-Geocoder plugin has its own spinner
- Tangram Play uses a spinner that's taken from the icon font it is using

**Comment by souperneon** [comment]
Can we document those and also the spinner in the button on developers?

**Comment by hanbyul-here** [comment]
there are two loading status for developer dashboard 
one is text changing for key status, the other one is for graph (which is generic svg from d3). It is purely generated from script.
 Web Map is using spin js with similar color theme of other icons (also generic).
wah we do have a lot of loading bar!

**Comment by souperneon** [comment]
@hanbyul-here do you wan to add the two you mentioned?

**Comment by hanbyul-here** [comment]
if our rule is not putting only-once-used element, probably loading bars on developer dashboard don't need to be there, but if we are trying to lay down everything we have to choose one, I can.

**Comment by souperneon** [comment]
if it's easy, I would put that in there. I bet this will be used in the future, at lease in the admin section?

**Comment by hanbyul-here** [comment]
they are purely generated from script (web map too) , so I will skip the loading bar from developer dashboard

**Comment by souperneon** [comment]
sounds good
