### ISSUE TITLE
Re-arrange navigation and intro text

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#125]
(continuing this issue after seeing the work on [the `ekta/navigation` branch](http://precog.mapzen.com/mapzen/styleguide/a58c7fbca1e0fd0cd6b69ce8fe523c111ae7495f/) vs. [current `master` branch](http://precog.mapzen.com/mapzen/styleguide/096e4e8af60c8f4cc0e7da4d33a537c9c0ac18d8/))
1. The top navigation suggests that non-web Brand or Content style guides might follow this one, and that they might eventually get the same top nav instead of external links to Github. That’s interesting.
2. Make sure that this part of the announcement (https://github.com/mapzen/styleguide/issues/116) is true by adding a prominent link to “How To” at the top:
   
   > To use the guide, visit https://mapzen.com/common/styleguide and follow the instructions at top to structure HTML and linked style and script resources.
3. Include complete minimum page skeleton (https://github.com/mapzen/styleguide/issues/106) to _How To_ area.
4. Links to sample pages from _introduction.html_ seem right. Maybe _introduction.html_ should actually be _index.html_?

**Comment by souperneon** [comment]
1. This navigation allows us to make a central place where a user internal/external can find all they need. I would say, let's start with this (and ignore the janky linking out from the top nav for content links) and see if it makes sense to people
2. I suggest we just remove 'at top'? (I marked it in the doc)
3. True. I wanted to discuss in our standup before we make the big change. Let's finalize today!

**Comment by migurski** [comment]
Thinking that sample pages should be a sub-nav under Introduction.

**Comment by souperneon** [comment]
https://github.com/mapzen/styleguide/issues/110
