### ISSUE TITLE
In bundled js, automatically handle affixed sub-navigation components

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#133]
Also, scrollspying

**Comment by hanbyul-here** [comment]
oh, I thought it is already there. can you point out the script that handles this part in documentation?

**Comment by louh** [comment]
A bunch of this needs to be taken out of documentation's base.js
https://github.com/mapzen/mapzen-docs-generator/blob/master/theme/js/base.js#L149-L197

**Comment by louh** [comment]
@hanbyul-here we can close this now yeah?

**Comment by hanbyul-here** [comment]
yes! :+1:
