### ISSUE TITLE
Rejigger How-To information

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#162]
- [x] Remove optional HTML5 elements (header, footer, main) from HTML boilerplate to trim it down.
- [x] Remove incorrect `blog.css` link from top of index.html.
- [x] Do we actually need all three levels of `div` tag? Seems a bit much.

**Comment by souperneon** [comment]
the three levels of div are as Lou defined "predictable spacing and layout". We would prefer people follow that and add their stuff inside those divs. I'll add a page structure drawing under the snippet to explain that better. :)

**Comment by migurski** [comment]
Heh, okay.

**Comment by souperneon** [comment]
https://github.com/mapzen/styleguide/pull/168 @louh all yours!
