### ISSUE TITLE
sidenav could be clearer

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/styleguide#164]
in my opinion it's not clear enough that the unbolded lines are children of the solid one above... primarily when initially loading a page.
once i clicked through a couple sections, it was perfectly clear how it worked.

possible solutions:
- indent the children
- animate them expanding on initial load

**Comment by souperneon** [comment]
that should be fixed on current master. Can you check?

**Comment by sleepylemur** [comment]
actually its slightly broken at the moment, but i was referring in general to how it works on documentation etc.

here's the slightly broken screenshot:
![image](https://cloud.githubusercontent.com/assets/5049698/12517863/115addc4-c103-11e5-9dc8-82d4a674c977.png)

**Comment by souperneon** [comment]
should get fixed with this https://github.com/mapzen/styleguide/pull/170

Adding a left highlight to the section you are on, is pretty clear. Indentation is another way of doing that. Is that just your preference or are you saying there is a bigger problem here?

**Comment by sleepylemur** [comment]
closing this. we can revisit if more people complain about sidenav clarity.
