### ISSUE TITLE
Deploy from master

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#172]
Talked with @sleepylemur; ensure @baldur is okay with this plan.

**Comment by baldur** [comment]
:+1: so long there is a way to verify that branches coming in aren't broken in some way

**Comment by migurski** [comment]
I’m thinking of two things: 
1. Asking people to [preview with Precog](https://github.com/mapzen/styleguide/blob/a425fea/README.md#contribute) for now.
2. Test automatically with something like Browserstack at some point in the future.
