### ISSUE TITLE
Reduce contrast on background diagonal lines in code snippets

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#185]
They make the text seem to vibrate. Reduce or remove? 

<img width="653" alt="pre" src="https://cloud.githubusercontent.com/assets/58730/12525038/3a0e3c6c-c116-11e5-89d1-33c651927a7a.png">

**Comment by hanbyul-here** [comment]
I like having coherent style with documentation site, but we can decrease the contrast, how do you think @souperneon  ( I decreased half in the pic) 
![screen shot 2016-01-25 at 12 11 57 pm](https://cloud.githubusercontent.com/assets/4583806/12558327/f0fec20a-c35c-11e5-8d0a-4c0b697d428a.png)

**Comment by souperneon** [comment]
we should decrease it overall. It has too much character right now and making the text hard to read.
@hanbyul-here where in the code can I play with it?

**Comment by hanbyul-here** [comment]
https://github.com/mapzen/styleguide/blob/master/src/stylesheets/project_specific/styleguidepage/styleguidepage.scss#L78

(This is specifically for styleguide to override xrayhtml style, let's start from there.)
