### ISSUE TITLE
Fix weirdness with image left/right on small screens

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#186]
Image right looks a bit odd on mobile. Also, consider "before"/"after" as terminology instead of "left"/"right" due to responsive squash?

![image](https://cloud.githubusercontent.com/assets/58730/12527550/57fda64c-c132-11e5-9edc-94d00bb3bce4.png)

**Comment by hanbyul-here** [comment]
This is from markup, so we put image box first even if image box is on right to make it look good at mobile, but obviously this is not intuitive way of writing markdown, so there was mistake about it. fixing it now.
