### ISSUE TITLE
styleguide breaks bootstrap sortable

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/styleguide#19]
specifically the arrows that show the sort direction are no longer rendering

**Comment by migurski** [comment]
This issue has been hanging around for a while. Is it important / worth doing?

**Comment by souperneon** [comment]
not mission critical but if you have time to investigate @louh

**Comment by sleepylemur** [comment]
it's only for admin so it doesn't matter that much, which is why i've been putting off finding a solution. i'll take a look
