### ISSUE TITLE
explain sidenav context

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/styleguide#204]
Trying to add the sidenav to admin I was confused how it fits into the page. If an example could be shown like: (not sure if this is correct)

``` html
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-3">
      <div class="toc">
        sidenav content here
      </div>
    </div>
    <div class="col-xs-12 col-md-9">
      main content here
    </div>
  </div>
</div>
```

**Comment by louh** [comment]
I think this is a good idea -- the sidenav theoretically doesn't care where it is, but we seem to be accepting the 3-column "standard" and it'd be good to indicate that.
