### ISSUE TITLE
Strategy for content in tables (especially for mobile)

### ISSUE THREAD

**Issue by rmglennon** [mapzen/styleguide#215]
Moving this from @souperneon's issue in mapzen-docs-generator now that we have a styleguide.

https://github.com/mapzen/mapzen-docs-generator/issues/72

Figure out some guidelines on creating tables (suggested number of columns and total width) so it is reasonably readable on mobile and doesn't look broken (see below)

![image](https://cloud.githubusercontent.com/assets/4380498/13128332/d24cad4c-d589-11e5-887b-6a237e7b09fd.png)

**Comment by hanbyul-here** [comment]
This problem is fixed with wrapper (scroll horizontal way when screen is small)
