### ISSUE TITLE
Add ability to go back to the top of the page

### ISSUE THREAD

**Issue by rmglennon** [mapzen/styleguide#216]
From this issue about the help system: https://github.com/mapzen/mapzen-docs-generator/issues/40

Please evaluate to see if this is something we should still do.

Original: Some of these topics are pretty long, and if you scroll to the end of a md file, the TOC won't scroll to the next topic in the TOC. So, you need a way to get back to the top of the page.

We could consider adding a "Back to top" button or keep the breadcrumbs (maybe TOC, too?) displaying on the page as you scroll.

Suggestion by @souperneon: Add an arrow on the right of the main content area
(See cartodb http://docs.cartodb.com/cartodb-editor.html#managing-your-data or gilt.com as examples)

**Comment by hanbyul-here** [comment]
as Lou replied to original issue, I wonder we really need it when toc is scrolling with your scroll, thoughts? @souperneon

**Comment by hanbyul-here** [comment]
We talked and we don't think we need it right now.
