### ISSUE TITLE
Extract nav manipulation into a separate function

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#328]
In order to complete navigation on Metro Extracts, it will be necessary to manipulate the header using data from a source other than XHR

Can we get this code into a separate function: https://github.com/mapzen/styleguide/blob/b951fedac/src/scripts/main-nav.js#L40-L57

It needs to be a global function, that looks something like:

```Javascript
function updateMapzenNavigation(id, nickname, avatar)
{
    ...
}
```

Connected to https://github.com/mapzen/metro-extracts/pull/283 and https://github.com/mapzen/website/issues/1259.

**Comment by hanbyul-here** [comment]
closed via https://github.com/mapzen/styleguide/pull/330
