### ISSUE TITLE
Header / footer stangeness for metro extracts

### ISSUE THREAD

**Issue by nvkelso** [mapzen/styleguide#352]
Who doesn't love avatars.github.com?

The avatar image works fine on main mapzen.com page.

![pasted image at 2017_03_01 04_10 pm](https://cloud.githubusercontent.com/assets/853051/23487340/3289b184-fe9a-11e6-8592-ee947ade20b6.png)

![pasted image at 2017_03_01 04_12 pm 1](https://cloud.githubusercontent.com/assets/853051/23487325/202f7c6c-fe9a-11e6-8e3b-a91c2ecb3454.png)

Another problem with "Who's On First" in the footer (bad ' )

![pasted image at 2017_03_01 04_12 pm](https://cloud.githubusercontent.com/assets/853051/23487326/204be35c-fe9a-11e6-87e2-e10f1f6bce0a.png)

**Comment by hanbyul-here** [comment]
Nav is fixed with https://github.com/mapzen/metro-extracts/commit/362838fab3a91b892f5134dec49b992a563cc890

I am still not sure what is wrong with footer 🤔

**Comment by rfriberg** [comment]
https://github.com/mapzen/website/pull/1440 should fix the footer issue.

**Comment by souperneon** [comment]
@nvkelso does everything look ok now?

**Comment by rfriberg** [comment]
mapzen/website/#1440 hasn't been merged, so this is not fixed yet.
