### ISSUE TITLE
Edit look and feel of slider to match pricing page

### ISSUE THREAD

**Issue by souperneon** [mapzen/styleguide#413]
<img width="334" alt="screen shot 2017-04-10 at 5 09 09 pm" src="https://cloud.githubusercontent.com/assets/6125224/24882843/8418a79a-1e10-11e7-957d-e4cb2b0d74be.png">

* Colors are subject to change :)

**Comment by louh** [comment]
Is this is still required for reference or should we close this? (Follow up issues in website#1617, this feels like a dupe at this point)
