### ISSUE TITLE
Set spacing for consecutive buttons

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#416]
The spacing between two consecutive buttons is one space character:

![screenshot 2017-04-12 10 46 23](https://cloud.githubusercontent.com/assets/2553268/24963719/602b680a-1f6d-11e7-84a6-ec4dc6becfe8.png)

HTML:
```html
<button class="btn btn-mapzen">Sign up for an account</button>
<button class="btn btn-white">Get started for free</button>
```

If you were to remove all whitespace between buttons tags, the space disappears and buttons would have zero margin between them. While it may be unnatural to write HTML this way, it can happen, especially if HTML files are minified during a build process. As a result it is necessary to specify exactly what the margin spacing ought to be if multiple buttons occur in a row.

The visual mockup for the above condition shows this:

![screenshot 2017-04-12 10 48 25](https://cloud.githubusercontent.com/assets/2553268/24963851/c5aff380-1f6d-11e7-8f0a-6043e48d1056.png)

**Comment by louh** [comment]
For mobile widths, adjacent buttons are collapsing to zero vertical space:

<img width="307" alt="screenshot 2017-04-12 12 45 22" src="https://cloud.githubusercontent.com/assets/2553268/24969223/fda87e5a-1f7d-11e7-82e8-6f9a68e1a75c.png">

**Comment by souperneon** [comment]
Let's use similar spacing guidelines and multipliers as here: https://github.com/mapzen/website/issues/1367
So, in this case I would say 12px would be ideal

**Comment by louh** [comment]
So the thing that I realized is that multiple buttons in sequence really need the `<div class="btn-group">` wrapper around them to space correctly.

It's shown in a code snippet in the styleguide, but not explained: https://mapzen.com/common/styleguide/design-elements.html#buttons

One of the issues here is the `btn-group` usage in Bootstrap means something specific - grouping buttons together into a single visually coherent component, not just as a way of organizing HTML elements. Since we don't actually do that, and `btn-group` fixes a margin of 10px, the best case scenario is probably making the spacing 12px regardless of whether or not a series of buttons is wrapped in `btn-group`. (My hunch is that in some cases a `btn-group` will paper over weird layout issues, but it shouldn't be required.)

Related to buttons, but not related to spacing: we should probably also document that buttons can also be `<a>` elements. This prevents a scenario in which things that are really links become `<button>` elements by accident, which require additional JS logic to do anything.
