### ISSUE TITLE
Mapzen logo jumpiness on mobile

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#421]
Hovering over the Mapzen logo in the navbar in a mobile-width viewport makes the logo jumpy:

![apr-13-2017 12-47-38](https://cloud.githubusercontent.com/assets/2553268/25014864/7e49469c-2047-11e7-8c52-4b042fca8022.gif)

**Comment by louh** [comment]
@rfriberg does this fit better in the website repo?

**Comment by rfriberg** [comment]
D'oh.  I probably introduced that with a change I pushed yesterday.  Nah. Leave it here. I'll fix.

Thanks!
