### ISSUE TITLE
Button with arrow link ("chromeless") has an inset shadow when pressed

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#431]
Should probably not be there.

**Comment by hanbyul-here** [comment]
I don't think this is only button with arrow link. I see `btn:active` style has box-shadow (but probably not that obvious because others have own color of being active unlike arrow button) We want all buttons not to have box shadow for `:active` status? @souperneon ?

**Comment by souperneon** [comment]
You're right! It just shows right away when there is no button chrome. Can we take it out of this one first? I am neutral on keeping it on other buttons. Anyone else care?

**Comment by louh** [comment]
Yeah, it's just most noticeable on the chromeless buttons, so the priority is just about removing it from there. I'm also neutral about it on other buttons.

Also I made the assumption that it was only the `a.btn:active`s but it's really on all `.btn:actives` (which includes `button.btn:active`) so I'll amend the title.
