### ISSUE TITLE
Investigate need for <article> around generic <ul> lists

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#441]

**Comment by louh** [comment]
@souperneon Do you know why we are replacing bullets on `<ul>` lists? They don't appear to do anything but be a smaller version of bullets

**Comment by souperneon** [comment]
Yeah, i think it had to do with sizing the bullets so they appeared vertically centered and the right size. Is there another way to achieve that?

**Comment by louh** [comment]
Are the default bullets not vertically centered, and is there something wrong with the default size?

**Comment by souperneon** [comment]
@louh happy to revisit… if you can post a screenshot without <article> that will be helpful.

**Comment by louh** [comment]
Sure. Here's a screenshot of the list from the styleguide, without the `<article>` wrapper:

<img width="205" alt="screenshot 2017-05-26 15 51 51" src="https://cloud.githubusercontent.com/assets/2553268/26510454/6752fd9c-422b-11e7-8a92-bd7e58bb2c3c.png">

Also, on the front page of the [styleguide](https://mapzen.com/common/styleguide/) we're using regular bullets, so you can see it in action

<img width="714" alt="screenshot 2017-05-26 15 52 14" src="https://cloud.githubusercontent.com/assets/2553268/26510518/a78b2ae2-422b-11e7-9251-ae47c72c160e.png">

**Comment by souperneon** [comment]
Super weird… I must be misremembering then. We can kill it! Thanks :)
