### ISSUE TITLE
Catalog sample pages to include

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#47]
Currently thinking:

Long-text docs pages like https://mapzen.com/documentation/search/ 
Blog posts and listings like https://mapzen.com/blog/ 
Data download services like https://mapzen.com/data/metro-extracts/ 
Project listings like https://mapzen.com/projects/ 
Project pages like https://mapzen.com/projects/tangram

**Comment by louh** [comment]
I think we got all of these now :+1:

**Comment by migurski** [comment]
- Long-text doc: https://github.com/mapzen/styleguide/blob/master/dist/samples/documentation.html
- Blog listing: https://github.com/mapzen/styleguide/blob/master/dist/samples/blog-main.html
- Blog post: https://github.com/mapzen/styleguide/blob/master/dist/samples/blog-post.html
- Data download: https://github.com/mapzen/styleguide/blob/master/dist/samples/data-borders.html
- Projects listing: https://github.com/mapzen/styleguide/blob/master/dist/samples/projects.html
- Project page: https://github.com/mapzen/styleguide/blob/master/dist/samples/projects-tangram.html
