### ISSUE TITLE
Catalog page elements to include

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#48]
Currently thinking: 

Developer key listings, or some precursor element?
Blog author credit boxes on listings and posts.
Sidebar and breadcrumb nav like in documentation.
Picture/description/link boxes like on project page.
Space for big-ass map views like on Tangram page.

**Comment by souperneon** [comment]
Horizontal Sub-navigation like in project pages.
Social share bar like on blog posts
Search box like on demos
Branded social bar like on demos
Pagination style (previous/next) like on blog posts and documentation pages
CTA for developer sign up like on documentation pages

**Comment by migurski** [comment]
We agreed that this issue should be resolved by creating a page and structure for one initial element, and followed up with separate tickets for others.

**Comment by souperneon** [comment]
leaving out developer key things, and map ui (search and scarab)… created individual issues for the rest
