### ISSUE TITLE
Create a disabled state for the `.btn-with-arrow` button

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#480]

**Comment by souperneon** [comment]
![button-link-states](https://cloud.githubusercontent.com/assets/6125224/26262865/4800b15a-3ca4-11e7-8cc4-2d340968a45f.png)

Just added it to the default reference sheet

**Comment by louh** [comment]
@souperneon It looks like the background/text color values for the secondary buttons are wrong, and I'm assuming from the images that nothing is changing.

**Comment by souperneon** [comment]
Correct. Ignore everything except the button with arrow I guess :P
