### ISSUE TITLE
Add polyfills for Fetch/Promise

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#499]
I'd like to open the possibility of providing certain polyfills for newer JavaScript syntax via the styleguide. (Similar in spirit to the rangeslider polyfill we added for old IE.)

Certain JavaScript APIs are really nice to have, and indeed, if you were writing for modern browsers only, you would never think twice about using them:

- Fetch API
- Promises (Fetch depends on this)
- `HTMLElement.classList`
- `Object.assign()`

None of these are supported (or fully supported) by any version of Internet Explorer. (They are supported by Edge.)

This means we are writing JavaScript in such a way that works around these limitations (assuming we had fully accounted for them at all, as many components were written prior to writing down our official browser support policy), for the purpose of supporting an older branch of browsers. This makes certain code much more complex than it needs to be, is harder to read and write as developers, and has a greater surface area for bugs.

I propose that we can write more modern JavaScript, and depend instead on polyfills to invisibly provide the modern functionality for older browsers. When we remove older browsers from support, we can simply remove the polyfills and be left with modern code. By providing polyfills in the styleguide, we ensure that every Mapzen site has the same baseline of JavaScript functionality out of the box.

This not a proposal to add _all_ the polyfills in the world, as this incurs a download size cost, and we should rightfully be concerned about blowing up the bundle size needlessly. Instead, we would only add polyfills for features that are (a) easy to polyfill in a transparent way (b) have a small footprint (c) be something that we actually use. In other words, we can consider each polyfill to see whether they provide high utility for a relatively low byte count.

JavaScript that we polyfill in this manner should be documented in the JavaScript portion of the styleguide documentation. Nothing should be magic or assumed. We are explicit about what we make available to the environment.

## Implementation

Under `./src/scripts`, make a new directory called `/polyfills`. The "main" script here is an `index.js` that `require()`s each polyfill, making it available to the global environment. In `./src/scripts/main.js`, we then `require('./polyfills/index')` to bring them all in.

cc @hanbyul-here @meghanhade @sleepylemur

**Comment by hanbyul-here** [comment]
I addressed my thoughts in person, but to summarize it : 
 - Considering `Fetch` is going to be used two times (one for navigation state check, the other for check apikeys that users have - We maybe can consolidate this into one call? this will be a separate issue though- ) in Styleguide for now, I am not sure this is right timing to include `fetch` polyfill.
- I haven't considered styleguide as a tool to offer more convenient development experience to users. Styleguide will offer  Polyfills embedded to users as a side effect, however, we should separate this from the functionality of Styleguide. (or we should reconsider the role of Styleguide)

I do agree that
- Considering Polyfills are based on Browser's native apis (unlike some dependencies that we decide to hide) , it would be right decisions for future ✨  Thanks for suggesting this! 
-This will provide better development experience.

I like the detail of implementation. I suggest to add the section of the browsers we decided to support, and what kind of Polyfills we offer through Styleguide. (as a side effect)
