### ISSUE TITLE
!BROKEN! FIX THIS

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/styleguide#53]
- [x] footer fonts became too thick
- [x] nav fonts became too thick

**Comment by souperneon** [comment]
@hanbyul-here are you taking care of all of these?

**Comment by migurski** [comment]
For the future, these should best be separate issues with meaningful names.

**Comment by hanbyul-here** [comment]
@souperneon nah, I & evan @sleepylemur decided to make a space to throw all errors here, I think @migurski  is right, will seperate this

**Comment by hanbyul-here** [comment]
seperated into https://github.com/mapzen/styleguide/issues/58, https://github.com/mapzen/styleguide/issues/57
