### ISSUE TITLE
nav has list bullets

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/styleguide#61]

**Comment by sleepylemur** [comment]
![image](https://cloud.githubusercontent.com/assets/5049698/12266467/59f251c4-b911-11e5-8409-928cae427409.png)

also affects bottom of blog page, and probably other places as well

![image](https://cloud.githubusercontent.com/assets/5049698/12266481/699dacae-b911-11e5-8e9f-5d4da68e32ff.png)

**Comment by louh** [comment]
Let's talk about this ASAP. New "standard" list styles are what's causing this, but what's probably less obvious is that it's [very common](http://getbootstrap.com/components/#nav-tabs) to use list elements, particularly the unordered list element `ul` to structure navigation and [collections](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul) of items.

Further reading:
https://css-tricks.com/navigation-in-lists-to-be-or-not-to-be/
https://css-tricks.com/wrapup-of-navigation-in-lists/

It's common enough _as structure_ that we might not want to assume that it's a human-readable bulleted list by default, but this seems to contradict earlier decisions for things like anchor (link) tags, so let's discuss.
