### ISSUE TITLE
documentation links too low on /developers

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/styleguide#62]
![image](https://cloud.githubusercontent.com/assets/5049698/12266367/d50fc6a8-b910-11e5-8be6-d9f7e8f6d546.png)

**Comment by louh** [comment]
I have comments on the original implementation of this, which may or may not be the relevant fix to make right now: basically, we should consider not expanding the line-height in order to achieve baseline alignment on text, which is not what's supposed to be used for.

**Comment by hanbyul-here** [comment]
@louh yeah, you are right, I remembered that I used flexbox, then saw rendering problems on mobile side, then changed back to use line-height. will look into it after styleguide.
