### ISSUE TITLE
documentation nav messed up

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/styleguide#63]
![image](https://cloud.githubusercontent.com/assets/5049698/12266414/0f974a8a-b911-11e5-8953-78ed4f98a05f.png)

spacing is all crazy, and also the font got slightly larger, though that's probably fine

**Comment by migurski** [comment]
Also seeing this manifestation with dropped list items:

<img width="1031" alt="dev" src="https://cloud.githubusercontent.com/assets/58730/12270616/d0135368-b90b-11e5-9e74-06f6227152e3.png">

**Comment by louh** [comment]
Those are covered in #61, #62

**Comment by migurski** [comment]
Can this be closed? Looks like it’s okay as of 97f66a2e195d: http://precog.mapzen.com/mapzen/styleguide/97f66a2e195d/samples/documentation.html

**Comment by louh** [comment]
It's so beautiful I could cry
