### ISSUE TITLE
Use CSS class names in styleguide

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#73]
For example, these should be `.mz-color` rather than `$mz-color` if I’m correctly understanding what’s happening here:

<img width="399" alt="color" src="https://cloud.githubusercontent.com/assets/58730/12310860/b563935a-ba07-11e5-922b-ef90f76f254a.png">

**Comment by souperneon** [comment]
.mz-color classes are what I created just for the styleguide (sigh) to give the row a background color. We don't do that anywhere on the site and it was confusing to expose the class without explaining that it was for coloring the background only.
The variable seemed more useful to use in making new css. 

Obviously there is room for both of those to exist. So I can create classes like "the color: $mz-red" if that's ideal?

**Comment by migurski** [comment]
The variable is a Sass thing, yes?

**Comment by louh** [comment]
Yes, it's a Sass/SCSS thing. It'll just exist even if we don't want to advertise it.

We had a brief conversation yesterday about the `.mz-color` classes which was that it really needed to make a distinction between background colors and text colors for it to be really useful.

**Comment by migurski** [comment]
Let’s make sure it’s not on the front page of the style guide, even if it exists in the source. Agreed that the color classes need a slightly smarter foreground!

**Comment by migurski** [comment]
I see these are in progress! There are a couple remaining on the front page, e.g. `.$mz-sans-serif` and then we can close out this ticket.

**Comment by souperneon** [comment]
https://github.com/mapzen/styleguide/pull/108
